# Generated by Django 5.2.4 on 2025-09-24 16:53

import django.db.models.deletion
import django_ckeditor_5.fields
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bioma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("AMAZONIA", "Amazônia"),
                            ("CAATINGA", "Caatinga"),
                            ("CERRADO", "Cerrado"),
                            ("MATA_ATLANTICA", "Mata Atlântica"),
                            ("PANTANAL", "Pantanal"),
                            ("PAMPA", "Pampa"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Nome do Bioma",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon file name",
                        max_length=100,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Label Menu", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Gerado automaticamente a partir do nome",
                        unique=True,
                    ),
                ),
                (
                    "geourl",
                    models.URLField(help_text="URL para geosjon", max_length=512),
                ),
            ],
            options={
                "verbose_name": "Bioma",
                "verbose_name_plural": "Biomas",
            },
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(max_length=512)),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("GEOJSON", "GeoJSON"),
                            ("WMS", "WMS (Web Map Service)"),
                            ("TILE", "Tile Layer (XYZ/Raster)"),
                            ("VECTOR", "Vector Tiles"),
                            ("WFS", "WFS (Web Feature Service)"),
                        ],
                        default="GEOJSON",
                        max_length=20,
                        verbose_name="Tipo de Camada",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("style", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaginaEstatica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("resumo", models.CharField(blank=True, max_length=160)),
                ("conteudo", django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Rótulo")),
                (
                    "anchor_id",
                    models.CharField(
                        blank=True,
                        help_text="ID da seção na página (ex: #visao-geral)",
                        max_length=50,
                        verbose_name="ID de Âncora",
                    ),
                ),
                (
                    "pagina",
                    models.ForeignKey(
                        blank=True,
                        help_text="Página estática associada",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.paginaestatica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Menu",
                "verbose_name_plural": "Itens de Menu",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Gerado automaticamente a partir do nome",
                        unique=True,
                    ),
                ),
                (
                    "bioma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temas",
                        to="escola.bioma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema do Bioma",
                "verbose_name_plural": "Temas dos Biomas",
                "ordering": ("order",),
                "abstract": False,
                "unique_together": {("bioma", "nome")},
            },
        ),
        migrations.CreateModel(
            name="RecursoPedagogico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ATIVIDADE", "Atividade"),
                            ("RECURSO", "Recurso Didático"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("resumo", models.CharField(blank=True, max_length=255)),
                ("texto", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "link_externo",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recursos_pedagogicos",
                        to="escola.tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso Pedagógico",
                "verbose_name_plural": "Recursos Pedagógicos",
            },
        ),
        migrations.CreateModel(
            name="LayerTemaOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.layer"
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.tema"
                    ),
                ),
            ],
            options={
                "ordering": ("tema", "order"),
                "abstract": False,
                "unique_together": {("tema", "layer")},
            },
        ),
        migrations.AddField(
            model_name="layer",
            name="temas",
            field=models.ManyToManyField(
                related_name="layers", through="escola.LayerTemaOrder", to="escola.tema"
            ),
        ),
        migrations.CreateModel(
            name="ImagemGaleria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="imagens/galeria/",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("resumo", models.CharField(blank=True, max_length=255)),
                ("tags", models.ManyToManyField(blank=True, to="escola.tag")),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="escola.tema",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Curiosidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("resumo", models.CharField(blank=True, max_length=255)),
                ("texto", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="imagens/curiosidades/",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="escola.tag")),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curiosidades",
                        to="escola.tema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conteudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("texto", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "tema",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteudo",
                        to="escola.tema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoEducativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("resumo", models.CharField(blank=True, max_length=255)),
                ("embed_url", models.URLField(max_length=512)),
                ("tags", models.ManyToManyField(blank=True, to="escola.tag")),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="escola.tema",
                    ),
                ),
            ],
        ),
    ]
