# Generated by Django 5.2.4 on 2025-09-24 21:16

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recursopedagogico",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="mediarecurso-pedagogico/",
            ),
        ),
        migrations.AddField(
            model_name="recursopedagogico",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="imagens/recurso-pedagogico/",
            ),
        ),
    ]
