# Generated by Django 5.2.4 on 2025-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioma',
            name='geourl',
            field=models.URLField(help_text='URL para geosjon', max_length=512),
        ),
        migrations.AlterField(
            model_name='layer',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='recursopedagogico',
            name='link_externo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='videoeducativo',
            name='embed_url',
            field=models.URLField(max_length=512),
        ),
    ]
