# Generated by Django 5.2.4 on 2025-11-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_recursopedagogico_file_recursopedagogico_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("slug", models.SlugField(blank=True, max_length=150, unique=True)),
                (
                    "centroide",
                    models.URLField(
                        blank=True,
                        help_text="URL do GeoJSON para centralizar o mapa",
                        max_length=512,
                        verbose_name="URL do Centroide/Feature",
                    ),
                ),
                (
                    "center_lon",
                    models.FloatField(
                        blank=True,
                        help_text="Longitude do centro inicial do mapa",
                        null=True,
                        verbose_name="Longitude do Centro",
                    ),
                ),
                (
                    "center_lat",
                    models.FloatField(
                        blank=True,
                        help_text="Latitude do centro inicial do mapa",
                        null=True,
                        verbose_name="Latitude do Centro",
                    ),
                ),
                (
                    "initial_zoom",
                    models.IntegerField(
                        default=6,
                        help_text="Nível de zoom inicial do mapa (1-20)",
                        verbose_name="Zoom Inicial",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Se o mapa está visível publicamente",
                        verbose_name="Publicado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Mapa",
                "verbose_name_plural": "Mapas",
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Se a camada está visível por padrão",
                        verbose_name="Visível",
                    ),
                ),
                (
                    "opacity",
                    models.FloatField(
                        default=1.0,
                        help_text="Opacidade da camada (0.0 a 1.0)",
                        verbose_name="Opacidade",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.layer"
                    ),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="escola.map"
                    ),
                ),
            ],
            options={
                "verbose_name": "Camada do Mapa",
                "verbose_name_plural": "Camadas do Mapa",
                "ordering": ["order"],
                "unique_together": {("map", "layer")},
            },
        ),
        migrations.AddField(
            model_name="map",
            name="layers",
            field=models.ManyToManyField(
                related_name="maps",
                through="escola.MapLayer",
                to="escola.layer",
                verbose_name="Camadas",
            ),
        ),
    ]
